# Generated by Django 3.2.9 on 2021-11-20 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=14, unique=True)),
                ('tipo', models.CharField(choices=[('A', 'Agua'), ('G', 'Gas'), ('I', 'Internet'), ('L', 'Luz')], default='A', max_length=1)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_vto', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=14, unique=True)),
                ('metodo', models.CharField(choices=[('D', 'Tarjeta de Debito'), ('C', 'Tarjeta de Credito'), ('E', 'Efectivo')], default='E', max_length=1)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
