# Generated by Django 3.2.9 on 2021-11-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_pago_app', '0002_alter_transaccion_numero_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='tipo',
            field=models.CharField(choices=[('Agua', 'Agua'), ('Gas', 'Gas'), ('Internet', 'Internet'), ('Luz', 'Luz')], default='Agua', max_length=8),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='metodo',
            field=models.CharField(choices=[('Tarjeta de Debito', 'Tarjeta de Debito'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=18),
        ),
    ]
